---
title: "Client Report"
output: word_document
params:
  client: NA
  period1: NA
  period2: NA
---

A report of all alerts for `r params$client ` in the analysis period `r params$period1 ` to `r params$period2 `

```{r echo=FALSE,eval=TRUE,warning=FALSE}
#browser()
library(lubridate)
library(ggplot2)
library(dplyr)
    client=params$client

    period1=params$period1
    period2=params$period2
    #client="CIDD705553"
    #period1="2016-03-01"
    #period2="2016-08-30"
    interval1=interval(period1,period2)
    
   custchart= unique.alerts%>%
      filter(remedy_customer_id==client)%>%
      filter(attack_start_time %within% interval1)%>%
      mutate(att_Month=lubridate::month(attack_start_time,label=TRUE))%>%
      group_by(att_Month,ai_alert_soc_status)%>%
      summarise(Status=n())

    clientInd=unique.alerts$industry[unique.alerts$remedy_customer_id==client]
   avgcust= unique.alerts%>%
      filter(industry==client)%>%
      filter(attack_start_time %within% interval1)%>%
      mutate(att_Month=lubridate::month(attack_start_time,label=TRUE))%>%
      group_by(att_Month,ai_alert_soc_status)%>%
      summarise(Status=n())
      
   
    ncust=unique.alerts %>% 
      filter(industry==clientInd)%>%
      filter(attack_start_time %within% interval1)%>%
      group_by(remedy_customer_id)%>%
      summarise(count=n())
      
      indcust=nrow(ncust)
      

        
        
        custchart=custchart%>%
          group_by(att_Month)%>%
          summarise(Total_Alerts=sum(Status))
        
        
        
        ggplot(data=custchart,aes(x=att_Month,y=Total_Alerts,fill=att_Month))+geom_bar(stat="identity")+
          geom_text(aes(att_Month,Total_Alerts,label=Total_Alerts),size=4)+
          #geom_point(data=avgcust,aes(x=att_Month,y=Avg_Alerts,group=1),size=1)+theme_light()+
          #geom_line(data=avgcust,aes(x=att_Month,y=Avg_Alerts,group=1),linetype="dashed",color="blue",size=1)+theme(legend.position ='none')+
          #geom_text(data=avgcust,aes(att_Month,Avg_Alerts+5,label=Avg_Alerts))+
          labs(x="Months",y="Total Alerts Generated")+ggtitle(label = paste("Total alerts generated by month for",client),subtitle = paste("Dotted line shows average alerts by Industry, n:",indcust))
        
      
```

This report will provide number  of False Positives (alerts that were closed and not escalated) for the client

```{r echo=FALSE,eval=TRUE,warning=FALSE}
#avgcust gives the average by industry
        #browser()
        fp=c("CLOSED","COMMENTED")
        
       custchart2= unique.alerts%>%
      filter(remedy_customer_id==client)%>%
      filter(attack_start_time %within% interval1)%>%
      mutate(att_Month=lubridate::month(attack_start_time,label=TRUE))%>%
      group_by(att_Month,ai_alert_soc_status)%>%
      summarise(Status=n())
        
      custchart3=custchart2%>%
          group_by(att_Month)%>%
          summarise(Total_Alerts=sum(Status))
        
        custchart1=custchart2%>%
          filter(ai_alert_soc_status %in% fp)%>%
          group_by(att_Month)%>%
          summarise(Total_Alerts=sum(Status))
        
        custchart$total=custchart1$Total_Alerts
        custchart$percent=round(custchart$total/custchart3$Total_Alerts*100,1)
        
        
        ggplot(data=custchart,aes(x=att_Month,y=percent,group=1))+geom_line(stat="identity",position = "identity",linetype="solid",color="blue")+
          geom_text(aes(att_Month,percent,label=paste0(percent,"%")),size=4)+
          #geom_point(data=avgcust,aes(x=att_Month,y=Avg_Alerts,group=1),size=1)+theme_light()+
          #geom_line(data=avgcust,aes(x=att_Month,y=avgpercent,group=1),linetype="dashed",color="green",size=1)+theme(legend.position ='none')+
          #geom_text(data=avgcust,aes(att_Month,avgpercent,label=paste0(avgpercent,"%")))+
          labs(x="Months",y="False Positives Percentage")+ggtitle(label = paste("% False Positives by month for",client),subtitle = paste("Dotted line shows average % false positives by Industry, n:",indcust))
        
```

